### ISSUE TITLE
Simple nlsolve

### ISSUE THREAD

**Issue by bradcarman** [SciML/SimpleDiffEq.jl#50]
Looking at the code, it seems this package doesn't support methods requiring non-linear iterations (i.e. non-identity mass matrix problems).   Would be good to have a simple implementation of the ImplicitEuler method.

I have a case where DifferentialEquations.jl is failing, so I wrote my own solver implementing Newton's method.  Surprisingly my solver is providing a correct solution, whereas ImplicitEuler, Rodas4, and others are all failing.  It would be really useful then to have a "simple" ImplicitEuler method I could use to check my model and compare/contrast with my solver and compare against DifferentialEquations.jl.

**Comment by ChrisRackauckas** [comment]
> Surprisingly my solver is providing a correct solution, whereas ImplicitEuler, Rodas4, and others are all failing

Are those using adaptivity? The nonlinear solver is really tied to the adaptivity scheme, so it's a bit rough to do adaptive=false on them.

But yes, this would be a good feature for debugging. Especially one that uses a globalizing nlsolve.

**Comment by bradcarman** [comment]
I'm using only discrete time steps, no adaptivity.  So for me, a simple discrete time stepping ImplicitEuler method would be great.

**Comment by ChrisRackauckas** [comment]
Yeah, so the algorithm you want for that case is something that doesn't tie rejection to adaptivity. What happens currently is the nonlinear solver tries to exit early as a sign of inefficiency, which then is used to decrease `dt` and the the convergence faster. Turning off adaptivity has a bad effect on that kind of connection, which is why normally stiff ODE solvers don't even allow a non-adaptive mode. We can probably do a few things to improve the non-adaptive mode, but to optimize that we probably want a good reference anyways.

We had that reference awhile back, but when we eliminated NLsolve.jl from the nonlinear solver handling we also eliminated those methods. Reviving them in SimpleDiffEq.jl would be a good way to do this. The reference code is:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/v5.17.0/src/perform_step/generic_implicit_perform_step.jl

with helpers:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/v5.17.0/src/caches/generic_implicit_caches.jl
https://github.com/SciML/OrdinaryDiffEq.jl/blob/v5.17.0/src/misc_utils.jl#L30-L40

Making the automatic differentiation work is nowadays a lot easier since you could use https://github.com/SciML/PreallocationTools.jl. If you want to just do the finite difference version though, I can easily add the automatic differentiation one.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SimpleNonlinearSolve.jl + changes to OrdinaryDiffEq have solved this.
